

import dynamic from "next/dynamic";

export const components = {
  appointment_booking_form: dynamic(() => import("./AppointmentBookingForm")),

  approach_overview: dynamic(() => import("./ApproachOverview")),
  card_grid: dynamic(() => import("./CardGrid")),
  case_study_grid: dynamic(() => import("./CaseStudyGrid")),
  contact_form_details: dynamic(() => import("./ContactFormDetails")),
  contact_form_with_image: dynamic(() => import("./ContactFormWithImage")),
  cta_centered: dynamic(() => import("./CtaCentered")),
  expertise_overview: dynamic(() => import("./ExpertiseOverview")),
  faq_list: dynamic(() => import("./FaqList")),
  feature_case_study: dynamic(() => import("./FeatureCaseStudy")),
  feature_list_image: dynamic(() => import("./FeatureListImage")),
  featured_article: dynamic(() => import("./FeaturedArticle")),
  featured_article_with_list: dynamic(
    () => import("./FeaturedArticleWithList"),
  ),
  half_media_content_info: dynamic(() => import("./HalfMediaContentInfo")),
  header: dynamic(() => import("./Header")),
  heading: dynamic(() => import("./Heading")),
  headline_stats: dynamic(() => import("./HeadlineStats")),
  hero_cta: dynamic(() => import("./HeroCta")),
  hero_with_bg_image: dynamic(() => import("./HeroWithBgImage")),
  hero_with_overlay: dynamic(() => import("./HeroWithOverlay")),
  icon_list: dynamic(() => import("./IconList")),
  image_form_split: dynamic(() => import("./ImageFormSplit")),
  image_text_columns: dynamic(() => import("./ImageTextColumns")),
  info_grid: dynamic(() => import("./InfoGrid")),
  info_with_images_grid: dynamic(() => import("./InfoWithImagesGrid")),
  informational_features: dynamic(() => import("./InformationalFeatures")),
  intro_featured_services: dynamic(() => import("./IntroFeaturedServices")),
  logo_bar: dynamic(() => import("./LogoBar")),
  main_text: dynamic(() => import("./MainText")),
  media_embed_2: dynamic(() => import("./MediaEmbed2")),
  media_grid_highlight: dynamic(() => import("./MediaGridHighlight")),
  page_header: dynamic(() => import("./PageHeader")),
  process_steps: dynamic(() => import("./ProcessSteps")),
  split_about_content: dynamic(() => import("./SplitAboutContent")),
  team_grid: dynamic(() => import("./TeamGrid")),
  team_showcase: dynamic(() => import("./TeamShowcase")),
  testimonial_carousel: dynamic(() => import("./TestimonialCarousel")),
  two_column_layout: dynamic(() => import("./TwoColumnLayout")),
  two_column_text_image_info: dynamic(() => import("./TwoColumnTextImageInfo")),
  video_embed: dynamic(() => import("./VideoEmbed")),
};

